### ISSUE TITLE
no valid OpenPGP data found. Trying to install on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by Mik3r** [leapcode/bitmask_client#893] opened 2015-09-06 01:37 UTC
root@machine:~# add-apt-repository "deb http://deb.bitmask.net/debian trusty main"
root@machine:~# wget -O- https://dl.bitmask.net/apt.key | apt-key add -
--2015-09-05 21:24:27--  https://dl.bitmask.net/apt.key
Resolving dl.bitmask.net (dl.bitmask.net)... 146.112.61.106, ::ffff:146.112.61.106
Connecting to dl.bitmask.net (dl.bitmask.net)|146.112.61.106|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name ‘dl.bitmask.net’.
To connect to dl.bitmask.net insecurely, use `--no-check-certificate'.
gpg: no valid OpenPGP data found.

can anybody help me understand what's wrong?

**Comment by elijh** [comment] 2015-09-06 07:47
You, or your network admin, is using OpenDNS. I think OpenDNS is a flaming pile of shit, but I digress. OpenDNS has decided that bitmask.net is a site that should be censored:

https://domain.opendns.com/bitmask.net

So, OpenDNS is causing dl.bitmask.net to be resolved incorrectly. That is why you get the message "ERROR: no certificate subject alternative name matches" because you are connecting to the wrong ip address. Disable OpenDNS and it should work fine.

**Closed by elijh** 2015-09-06 07:47 UTC

**Comment by micah** [comment] 2015-09-08 14:10
I'll note that this only happens with OpenDNS' FamilyShield service
which has you setup your resolver to use:

208.67.222.123
208.67.220.123

With these configured, I can confirm that opendns is hijacking that
domain...

if you use the standard opendns service, you will use different
nameservers:

208.67.222.222
208.67.220.220

these do not do the hijacking.

**Comment by Mik3r** [comment] 2015-09-13 01:58
After I disabled any filter on OpenDNS, I was able to install Bitmask but now every time I click the icon nothing happens.

Thanks for your work

On September 8, 2015 10:10:51 AM EDT, micah <notifications@github.com> wrote:
>
>I'll note that this only happens with OpenDNS' FamilyShield service
>which has you setup your resolver to use:
>
>208.67.222.123
>208.67.220.123
>
>With these configured, I can confirm that opendns is hijacking that
>domain...
>
>if you use the standard opendns service, you will use different
>nameservers:
>
>208.67.222.222
>208.67.220.220
>
>these do not do the hijacking.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/leapcode/bitmask_client/issues/893#issuecomment-138571032

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Mik3r** [comment] 2015-09-13 01:58
After I disabled any filter on OpenDNS, I was able to install Bitmask but now every time I click the icon nothing happens.



On September 8, 2015 10:10:51 AM EDT, micah <notifications@github.com> wrote:
>
>I'll note that this only happens with OpenDNS' FamilyShield service
>which has you setup your resolver to use:
>
>208.67.222.123
>208.67.220.123
>
>With these configured, I can confirm that opendns is hijacking that
>domain...
>
>if you use the standard opendns service, you will use different
>nameservers:
>
>208.67.222.222
>208.67.220.220
>
>these do not do the hijacking.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/leapcode/bitmask_client/issues/893#issuecomment-138571032

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by elijh** [comment] 2015-09-16 22:13
can you provide more details? which icon are you clicking on?

**Comment by Mik3r** [comment] 2015-09-17 00:09
I installed Bitmask following the instructions for Ubuntu 14.04 LTS provided on https://bitmask.net/en/install/linux.  After installation every time I click on Bitmask icon, the mouse cursor just changes to busy cursor for a couple seconds but nothing happens.

When I run bitmask on the terminal nothing happens.
This is the output of bitmask --debug:
2015-09-16 19:57:00,693 - DEBUG    - L#51   : leap:create_logger() - Console handler plugged!
2015-09-16 19:57:00,693 - DEBUG    - L#58   : leap:create_logger() - Leap handler plugged!
2015-09-16 19:57:00,693 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-] Log opened.
2015-09-16 19:57:00,700 - DEBUG    - L#72   : leap.bitmask.util.requirement_checker:check_requirements() - Checking requirements...
2015-09-16 19:57:00,700 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - requests>=1.1.0 ... OK
2015-09-16 19:57:00,701 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - srp>=1.0.2 ... OK
2015-09-16 19:57:00,701 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - pyopenssl ... OK
2015-09-16 19:57:00,701 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - python-dateutil ... OK
2015-09-16 19:57:00,701 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - psutil ... OK
2015-09-16 19:57:00,701 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - ipaddr ... OK
2015-09-16 19:57:00,701 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - python-daemon # this should not be needed for Windows. ... OK
2015-09-16 19:57:00,701 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - keyring ... OK
2015-09-16 19:57:00,701 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - zope.proxy ... OK
2015-09-16 19:57:00,701 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - pyzmq ... OK
2015-09-16 19:57:00,702 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - leap.common>=0.3.7 ... OK
2015-09-16 19:57:00,702 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - leap.soledad.client>=0.6.0 ... OK
2015-09-16 19:57:00,702 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - leap.keymanager>=0.3.8 ... OK
2015-09-16 19:57:00,702 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - leap.mail>=0.3.9 ... OK
2015-09-16 19:57:00,702 - DEBUG    - L#100  : leap.bitmask.util.requirement_checker:check_requirements() - oauth ... OK
2015-09-16 19:57:00,702 - DEBUG    - L#102  : leap.bitmask.util.requirement_checker:check_requirements() - Done
2015-09-16 19:57:00,702 - INFO     - L#174  : leap:start_app() - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2015-09-16 19:57:00,702 - INFO     - L#175  : leap:start_app() - Bitmask version 0.8.1
2015-09-16 19:57:00,702 - INFO     - L#176  : leap:start_app() - leap.mail version 0.3.11
2015-09-16 19:57:00,702 - INFO     - L#177  : leap:start_app() - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2015-09-16 19:57:00,702 - INFO     - L#179  : leap:start_app() - Starting app
2015-09-16 19:57:00,703 - DEBUG    - L#63   : leap.bitmask.backend.backend_proxy:__init__() - Connecting to server...
2015-09-16 19:57:00,703 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-] Traceback (most recent call last):
2015-09-16 19:57:00,703 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-]   File "/usr/bin/bitmask", line 9, in <module>
2015-09-16 19:57:00,703 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-]     load_entry_point('leap.bitmask==0.8.1', 'console_scripts', 'bitmask')()
2015-09-16 19:57:00,703 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-]   File "/usr/lib/python2.7/dist-packages/leap/bitmask/app.py", line 181, in start_app
2015-09-16 19:57:00,703 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-]     backend_running = BackendProxy().check_online()
2015-09-16 19:57:00,703 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-]   File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/backend_proxy.py", line 75, in __init__
2015-09-16 19:57:00,703 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-]     socket.curve_serverkey = public
2015-09-16 19:57:00,704 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-]   File "/usr/lib/python2.7/dist-packages/zmq/sugar/attrsettr.py", line 29, in __setattr__
2015-09-16 19:57:00,704 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-]     self._set_attr_opt(upper_key, opt, value)
2015-09-16 19:57:00,704 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-]   File "/usr/lib/python2.7/dist-packages/zmq/sugar/attrsettr.py", line 33, in _set_attr_opt
2015-09-16 19:57:00,704 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-]     self.set(opt, value)
2015-09-16 19:57:00,704 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-]   File "socket.pyx", line 314, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:3278)
2015-09-16 19:57:00,704 - DEBUG    - L#53   : leap:write() - 2015-09-16 19:57:00-0400 [-] TypeError: expected bytes, got: None
